//fetch media
export const SAVE_MUSIC_LIST = 'SAVE_MUSIC_LIST'
export const SAVE_ALBUM_LIST = 'SAVE_ALBUM_LIST'
export const SAVE_TOPIC_LIST = 'SAVE_TOPIC_LIST'
export const SAVE_BANNER_LIST = 'SAVE_BANNER_LIST'
export const SAVE_LINK_ALBUM_LIST = 'SAVE_LINK_ALBUM_LIST'
export const SAVE_SEARCH_MUSIC_LIST = 'SAVE_SEARCH_MUSIC_LIST'
export const SAVE_LINK_TOPIC_LIST = 'SAVE_LINK_TOPIC_LIST'
export const SAVE_MUSIC_OF_ALBUM = 'SAVE_MUSIC_OF_ALBUM'
export const SAVE_ALBUM_OF_TOPIC = 'SAVE_ALBUM_OF_TOPIC'
//fetch habit
export const SAVE_HABIT_PLAN = 'SAVE_HABIT_PLAN'
export const SAVE_HABIT_PLAN_EVENT = 'SAVE_HABIT_PLAN_EVENT'
//fetch toy
export const SAVE_TOY_PLAN = 'SAVE_TOY_PLAN'
//visibility
export const FETCH_NOTICE = 'FETCH_NOTICE'
export const SCENE_TREE = 'SCENE_TREE'
//home
export const SAVE_DATA_SITUATION = 'SAVE_DATA_SITUATION'
export const SAVE_USER_LIST = 'SAVEZ_USER_LIST'
//voice
export const SAVE_VOICE_LIST = 'SAVE_VOICE_LIST'
export const SAVE_CORPUS_LIST = 'SAVE_CORPUS_LIST'
export const SAVE_FIRST_SCENE_LIST = 'SAVE_FIRST_SCENE_LIST'
export const SAVE_SECOND_SCENE_LIST ='SAVE_SECOND_SCENE_LIST'
export const SAVE_ALL_FIRST_SCENE_LIST = 'SAVE_ALL_FIRST_SCENE_LIST'
export const SAVE_ALL_SECOND_SCENE_LIST = 'SAVE_ALL_SECOND_SCENE_LIST'
export const SAVE_ALL_SCENE = 'SAVE_ALL_SCENE'
