//fetchData
export const SAVE_MUSIC_LIST = 'SAVE_MUSIC_LIST'
export const SAVE_ALBUM_LIST = 'SAVE_ALBUM_LIST'
export const SAVE_TOPIC_LIST = 'SAVE_TOPIC_LIST'
export const SAVE_BANNER_LIST = 'SAVE_BANNER_LIST'
