//fetch media
export const SAVE_MUSIC_LIST = 'SAVE_MUSIC_LIST'
export const SAVE_ALBUM_LIST = 'SAVE_ALBUM_LIST'
export const SAVE_TOPIC_LIST = 'SAVE_TOPIC_LIST'
export const SAVE_BANNER_LIST = 'SAVE_BANNER_LIST'
export const SAVE_LINK_ALBUM_LIST = 'SAVE_LINK_ALBUM_LIST'
export const SAVE_SEARCH_MUSIC_LIST = 'SAVE_SEARCH_MUSIC_LIST'
export const SAVE_LINK_TOPIC_LIST = 'SAVE_LINK_TOPIC_LIST'
//fetch habit
export const SAVE_HABIT_PLAN = 'SAVE_HABIT_PLAN'
export const SAVE_HABIT_PLAN_EVENT = 'SAVE_HABIT_PLAN_EVENT'
//fetch toy
export const SAVE_TOY_PLAN = 'SAVE_TOY_PLAN'
//visibility
export const FETCH_NOTICE = 'FETCH_NOTICE'
//home
export const SAVE_DATA_SITUATION = 'SAVE_DATA_SITUATION'
export const SAVE_USER_LIST = 'SAVEZ_USER_LIST'
//voice
export const SAVE_VOICE_LIST = 'SAVE_VOICE_LIST'
